{{- if .Values.persistence.enabled }}
{{- range .Values.persistence.claims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-nginx.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" | quote }}
  storageClassName: {{ .storageClass | default "local-path" | quote }}
  resources:
    requests:
      storage: {{ .size | default "10Gi" | quote }}
---
{{- end }}
{{- end }}
